language: node_js

node_js:
  - "10"

env:
  - APP_VERSION=$(yarn run -s version)

services:
  - docker

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn run lint

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_REPOSITORY:$APP_VERSION -t $DOCKER_REPOSITORY:latest .

deploy:
  skip_cleanup: true
  - provider: script
    script: docker push $DOCKER_REPOSITORY
    on:
      branch:
        - master
