language: node_js

node_js:
  - "lts/*"

env:
  - PACKAGE_VERSION=$(npm --loglevel silent run version)

services:
  - mysql
  - redis-server
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install -q

before_script:
  - mysql -e 'CREATE DATABASE birthday;'
  - cp config/travis_ci.js config/local.js

script:
  - npm run eslint
  - npm run test
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls

after_success:
  - cp config/docker.js config/local.js
  - docker build -t $DOCKER_REPOSITORY:$PACKAGE_VERSION -t $DOCKER_REPOSITORY:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_REPOSITORY
