env = 'development'
debug = true

[server]
host = 'localhost'
port = 3000
baseUrl = 'http://localhost:3000/'

[logger]
level = 'debug'

[redis]
host = 'localhost'
port = 6379
keyPrefix = 'v2ray'

[mysql]
host = 'localhost'
port = 3306
username = 'root'
password = 'root'
database = 'v2ray'

[wechat]
corpId = 'wx4e2c2b771c467c9f'
agentId = 0
secret = 'k7TGD8xJLDU6-sPH3NwY0eTs2oBPyAINMdbSbGN80fuEt01UK0Z8dWzhm7crgkz7'
